/**
 * CONTROLLED PRODUCTION CONTAMINATION RECOVERY SCRIPT
 *
 * Requirements:
 * 1. Plan mode must be strictly read-only (--plan).
 * 2. Apply mode must require ALL of:
 *    - APPLY_PRODUCTION_RECOVERY=true
 *    - EXPECTED_FIREBASE_PROJECT_ID=gen-lang-client-0195097895
 *    - EXPECTED_FIRESTORE_DATABASE_ID=ai-studio-efluz-4c6c88a6-697e-4fdf-82ed-45fec68ca34d
 *    - RECOVERY_PLAN_HASH=<hash generated by plan mode>
 * 3. Before applying, re-read every affected document and compare its content hash with the plan.
 * 4. Back up every affected document before modification (locally and under recovery_backups/<runId>/documents).
 * 5. Use Firestore batches of at most 400 operations.
 * 6. Never perform a full collection delete.
 * 7. Never delete audit logs.
 * 8. Add one new audit log with actorUserId: 'system-recovery-2026-09-14'.
 */

import fs from 'fs';
import path from 'path';
import crypto from 'crypto';
import { initializeFirebaseAdmin, getFirebaseStatus, getFirestoreDb } from '../firebase/admin';
import { COLLECTIONS } from '../firebase/collections';

const EXPECTED_PROD_PROJECT_ID = 'gen-lang-client-0195097895';
const EXPECTED_PROD_DATABASE_ID = 'ai-studio-efluz-4c6c88a6-697e-4fdf-82ed-45fec68ca34d';
const SEASON_ID = 'season-2026-27';

interface DocumentState {
  collection: string;
  docId: string;
  path: string;
  exists: boolean;
  data: any;
  contentHash: string;
}

interface PlannedOperation {
  op: 'delete' | 'set' | 'update';
  collection: string;
  docId: string;
  path: string;
  payload?: any;
  currentData: any;
  exists: boolean;
  contentHash: string;
  reason: string;
}

interface RecoveryPlan {
  projectId: string;
  databaseId: string;
  seasonId: string;
  generatedAt: string;
  planHash: string;
  candidateResolutions: {
    arsenal: any;
    sunderland: any;
  };
  operations: PlannedOperation[];
}

function computeHash(obj: any): string {
  const str = JSON.stringify(obj || null, Object.keys(obj || {}).sort());
  return crypto.createHash('sha256').update(str).digest('hex');
}

async function fetchDocumentState(db: any, collection: string, docId: string): Promise<DocumentState> {
  const docRef = db.collection(collection).doc(docId);
  const snap = await docRef.get();
  const exists = snap.exists;
  const data = exists ? snap.data() : null;
  return {
    collection,
    docId,
    path: `${collection}/${docId}`,
    exists,
    data,
    contentHash: computeHash(data),
  };
}

export async function runRecovery() {
  const args = process.argv.slice(2);
  const isPlanMode = args.includes('--plan');
  const isApplyMode = args.includes('--apply');

  if (!isPlanMode && !isApplyMode) {
    console.error('❌ Usage:');
    console.error('  Plan mode:  tsx src/server/scripts/applyProductionContaminationRecovery.ts --plan');
    console.error('  Apply mode: tsx src/server/scripts/applyProductionContaminationRecovery.ts --apply');
    process.exit(1);
  }

  const { info } = initializeFirebaseAdmin();
  const status = getFirebaseStatus();

  console.log('================================================================');
  console.log(`    CONTROLLED PRODUCTION RECOVERY — ${isPlanMode ? 'PLAN MODE' : 'APPLY MODE'}`);
  console.log('================================================================');
  console.log(`Firebase Project:  ${status.projectId}`);
  console.log(`Firestore Database: ${status.databaseId}`);
  console.log(`Mode:               ${status.authMode}`);

  if (status.projectId !== EXPECTED_PROD_PROJECT_ID) {
    console.error(`❌ Project ID mismatch: expected ${EXPECTED_PROD_PROJECT_ID}, got ${status.projectId}`);
    process.exit(1);
  }
  if (status.databaseId !== EXPECTED_PROD_DATABASE_ID) {
    console.error(`❌ Database ID mismatch: expected ${EXPECTED_PROD_DATABASE_ID}, got ${status.databaseId}`);
    process.exit(1);
  }

  const db = getFirestoreDb();
  const now = new Date().toISOString();

  // Guard: If recovery audit record gKupceWRkMdnVauUyXba already exists, abort --apply
  const auditSnap = await db.collection(COLLECTIONS.AUDIT_LOGS).doc('gKupceWRkMdnVauUyXba').get();
  if (auditSnap.exists) {
    console.error('❌ RECOVERY_ALREADY_APPLIED: Recovery audit record gKupceWRkMdnVauUyXba already exists.');
    console.error('The old full recovery script must never execute twice.');
    console.error('Only the new status-correction script (correctRecoveredOccupancyStatuses.ts) may repair the status values.');
    if (isApplyMode) {
      process.exit(1);
    }
  }

  // 1. Inspect Arsenal and Sunderland Candidates
  console.log('\n[PHASE 1] Inspecting Ownership Candidates for Arsenal and Sunderland...');
  const candUserIds = ['user-100001', 'user-7460059265', 'user-100002', 'user-6128910148'];
  const userStates: Record<string, any> = {};

  for (const uid of candUserIds) {
    const uDoc = await db.collection(COLLECTIONS.USERS).doc(uid).get();
    userStates[uid] = uDoc.exists ? uDoc.data() : null;
  }

  // Arsenal Evidence
  const arsenalCand1 = userStates['user-100001'];
  const arsenalCand2 = userStates['user-7460059265'];
  const isUser100001Test =
    arsenalCand1?.username === 'manager_arsenal' ||
    arsenalCand1?.firstName === 'Mikel' ||
    arsenalCand1?.telegramId === '100001';

  if (!isUser100001Test) {
    console.error('❌ MANUAL_OWNER_SELECTION_REQUIRED: Insufficient evidence for Arsenal candidate user-100001');
    process.exit(1);
  }

  const arsenalResolution = {
    clubId: 'club-arsenal',
    selectedOwnerUserId: 'user-7460059265',
    selectedOwnerUsername: arsenalCand2?.username,
    selectedOwnerName: arsenalCand2?.firstName,
    disqualifiedCandidateUserId: 'user-100001',
    disqualificationReason: 'Documented test user created by verifyTournamentArchitecture.ts (username manager_arsenal, Mikel)',
  };
  console.log(`  ✓ Arsenal Owner Confirmed: ${arsenalResolution.selectedOwnerUserId} (@${arsenalResolution.selectedOwnerUsername})`);

  // Sunderland Evidence
  const sunderlandCand1 = userStates['user-100002'];
  const sunderlandCand2 = userStates['user-6128910148'];
  const isUser100002Test =
    sunderlandCand1?.username === 'manager_chelsea' ||
    sunderlandCand1?.firstName === 'Enzo' ||
    sunderlandCand1?.telegramId === '100002';

  if (!isUser100002Test) {
    console.error('❌ MANUAL_OWNER_SELECTION_REQUIRED: Insufficient evidence for Sunderland candidate user-100002');
    process.exit(1);
  }

  const sunderlandResolution = {
    clubId: 'club-sunderland',
    selectedOwnerUserId: 'user-6128910148',
    selectedOwnerUsername: sunderlandCand2?.username,
    selectedOwnerName: sunderlandCand2?.firstName,
    disqualifiedCandidateUserId: 'user-100002',
    disqualificationReason: 'Documented test user created by verifyTournamentArchitecture.ts (username manager_chelsea, Enzo)',
  };
  console.log(`  ✓ Sunderland Owner Confirmed: ${sunderlandResolution.selectedOwnerUserId} (@${sunderlandResolution.selectedOwnerUsername})`);

  // 2. Build Plan of Operations
  console.log('\n[PHASE 2] Building Targeted Operations Plan...');
  const operations: PlannedOperation[] = [];

  // Helper to schedule deletion
  async function planDelete(col: string, docId: string, reason: string) {
    const current = await fetchDocumentState(db, col, docId);
    if (current.exists) {
      operations.push({
        op: 'delete',
        collection: col,
        docId,
        path: current.path,
        currentData: current.data,
        exists: current.exists,
        contentHash: current.contentHash,
        reason,
      });
    }
  }

  // Helper to schedule set/update
  async function planSet(col: string, docId: string, payload: any, reason: string) {
    const current = await fetchDocumentState(db, col, docId);
    operations.push({
      op: current.exists ? 'update' : 'set',
      collection: col,
      docId,
      path: current.path,
      payload,
      currentData: current.data,
      exists: current.exists,
      contentHash: current.contentHash,
      reason,
    });
  }

  // PART 4: High-confidence Club Recovery: Deportivo Alavés
  await planDelete(
    COLLECTIONS.USER_MEMBERSHIPS,
    `${SEASON_ID}_audit-claimant-1789324395032`,
    'Synthetic claimant user membership for Alaves'
  );
  const alavesLegitClaimedAt = '2026-09-14T11:39:32.658Z';
  await planSet(
    COLLECTIONS.CLUBS,
    'club-alaves',
    {
      isTaken: true,
      claimedByUserId: 'user-1238738998',
      claimedAt: alavesLegitClaimedAt,
      recoveredAt: now,
      updatedAt: now,
    },
    'Restore legitimate owner user-1238738998 to club-alaves'
  );
  await planSet(
    COLLECTIONS.CLUB_OCCUPANCIES,
    `${SEASON_ID}_club-alaves`,
    {
      seasonId: SEASON_ID,
      clubId: 'club-alaves',
      userId: 'user-1238738998',
      status: 'active',
      statusSeason: `active_${SEASON_ID}`,
      claimedAt: alavesLegitClaimedAt,
      recoveredAt: now,
      updatedAt: now,
    },
    'Restore legitimate occupancy for club-alaves'
  );
  await planSet(
    COLLECTIONS.CLUB_MEMBERSHIPS,
    `${SEASON_ID}_club-alaves`,
    {
      seasonId: SEASON_ID,
      clubId: 'club-alaves',
      userId: 'user-1238738998',
      status: 'active',
      claimedAt: alavesLegitClaimedAt,
      recoveredAt: now,
      updatedAt: now,
    },
    'Restore legitimate club membership for club-alaves'
  );
  await planSet(
    COLLECTIONS.USER_MEMBERSHIPS,
    `${SEASON_ID}_user-1238738998`,
    {
      seasonId: SEASON_ID,
      clubId: 'club-alaves',
      userId: 'user-1238738998',
      status: 'active',
      claimedAt: alavesLegitClaimedAt,
      recoveredAt: now,
      updatedAt: now,
    },
    'Restore legitimate user membership for user-1238738998'
  );

  // PART 4: High-confidence Club Recovery: FC Barcelona
  await planDelete(
    COLLECTIONS.USER_MEMBERSHIPS,
    `${SEASON_ID}_audit-claimant-1`,
    'Synthetic claimant user membership for Barcelona'
  );
  const barcaLegitClaimedAt = '2026-09-11T18:51:28.930Z';
  await planSet(
    COLLECTIONS.CLUBS,
    'club-barcelona',
    {
      isTaken: true,
      claimedByUserId: 'user-8117945434',
      claimedAt: barcaLegitClaimedAt,
      recoveredAt: now,
      updatedAt: now,
    },
    'Restore legitimate owner user-8117945434 to club-barcelona'
  );
  await planSet(
    COLLECTIONS.CLUB_OCCUPANCIES,
    `${SEASON_ID}_club-barcelona`,
    {
      seasonId: SEASON_ID,
      clubId: 'club-barcelona',
      userId: 'user-8117945434',
      status: 'active',
      statusSeason: `active_${SEASON_ID}`,
      claimedAt: barcaLegitClaimedAt,
      recoveredAt: now,
      updatedAt: now,
    },
    'Restore legitimate occupancy for club-barcelona'
  );
  await planSet(
    COLLECTIONS.CLUB_MEMBERSHIPS,
    `${SEASON_ID}_club-barcelona`,
    {
      seasonId: SEASON_ID,
      clubId: 'club-barcelona',
      userId: 'user-8117945434',
      status: 'active',
      claimedAt: barcaLegitClaimedAt,
      recoveredAt: now,
      updatedAt: now,
    },
    'Restore legitimate club membership for club-barcelona'
  );
  await planSet(
    COLLECTIONS.USER_MEMBERSHIPS,
    `${SEASON_ID}_user-8117945434`,
    {
      seasonId: SEASON_ID,
      clubId: 'club-barcelona',
      userId: 'user-8117945434',
      status: 'active',
      claimedAt: barcaLegitClaimedAt,
      recoveredAt: now,
      updatedAt: now,
    },
    'Restore legitimate user membership for user-8117945434'
  );

  // PART 5: Release clubs with no legitimate owner
  // 1. Racing Santander
  await planDelete(COLLECTIONS.USER_MEMBERSHIPS, `${SEASON_ID}_audit-claimant-1789380938103`, 'Synthetic user membership for Racing Santander');
  await planDelete(COLLECTIONS.CLUB_OCCUPANCIES, `${SEASON_ID}_club-racing-santander`, 'Synthetic occupancy for Racing Santander');
  await planDelete(COLLECTIONS.CLUB_MEMBERSHIPS, `${SEASON_ID}_club-racing-santander`, 'Contaminated club membership for Racing Santander');
  await planSet(
    COLLECTIONS.CLUBS,
    'club-racing-santander',
    {
      claimedByUserId: null,
      claimedAt: null,
      isTaken: false,
      recoveredAt: now,
      updatedAt: now,
    },
    'Release unowned club-racing-santander'
  );

  // 2. Málaga CF
  await planDelete(COLLECTIONS.USER_MEMBERSHIPS, `${SEASON_ID}_audit-claimant-1789380340426`, 'Synthetic user membership for Malaga');
  await planDelete(COLLECTIONS.CLUB_OCCUPANCIES, `${SEASON_ID}_club-malaga`, 'Synthetic occupancy for Malaga');
  await planDelete(COLLECTIONS.CLUB_MEMBERSHIPS, `${SEASON_ID}_club-malaga`, 'Contaminated club membership for Malaga');
  await planSet(
    COLLECTIONS.CLUBS,
    'club-malaga',
    {
      claimedByUserId: null,
      claimedAt: null,
      isTaken: false,
      recoveredAt: now,
      updatedAt: now,
    },
    'Release unowned club-malaga'
  );

  // 3. RCD Mallorca
  await planDelete(COLLECTIONS.USER_MEMBERSHIPS, `${SEASON_ID}_audit-claimant-1789381098598`, 'Synthetic user membership for Mallorca');
  await planDelete(COLLECTIONS.CLUB_OCCUPANCIES, `${SEASON_ID}_club-mallorca`, 'Synthetic occupancy for Mallorca');
  await planDelete(COLLECTIONS.CLUB_MEMBERSHIPS, `${SEASON_ID}_club-mallorca`, 'Contaminated club membership for Mallorca');
  await planSet(
    COLLECTIONS.CLUBS,
    'club-mallorca',
    {
      claimedByUserId: null,
      claimedAt: null,
      isTaken: false,
      recoveredAt: now,
      updatedAt: now,
    },
    'Release unowned club-mallorca'
  );

  // PART 6: Arsenal and Sunderland test cleanup & legitimate confirmation
  await planDelete(COLLECTIONS.USER_MEMBERSHIPS, `${SEASON_ID}_user-100001`, 'Test user membership for user-100001 (Arsenal test)');
  await planDelete(COLLECTIONS.USER_MEMBERSHIPS, `${SEASON_ID}_user-regression-test-a`, 'Regression test membership for Arsenal');
  const arsenalClaimedAt = '2026-09-14T12:20:09.407Z';
  await planSet(
    COLLECTIONS.CLUBS,
    'club-arsenal',
    {
      isTaken: true,
      claimedByUserId: 'user-7460059265',
      claimedAt: arsenalClaimedAt,
      recoveredAt: now,
      updatedAt: now,
    },
    'Confirm legitimate owner user-7460059265 for Arsenal'
  );
  await planSet(
    COLLECTIONS.CLUB_OCCUPANCIES,
    `${SEASON_ID}_club-arsenal`,
    {
      seasonId: SEASON_ID,
      clubId: 'club-arsenal',
      userId: 'user-7460059265',
      status: 'active',
      statusSeason: `active_${SEASON_ID}`,
      claimedAt: arsenalClaimedAt,
      recoveredAt: now,
      updatedAt: now,
    },
    'Confirm legitimate occupancy for Arsenal'
  );
  await planSet(
    COLLECTIONS.CLUB_MEMBERSHIPS,
    `${SEASON_ID}_club-arsenal`,
    {
      seasonId: SEASON_ID,
      clubId: 'club-arsenal',
      userId: 'user-7460059265',
      status: 'active',
      claimedAt: arsenalClaimedAt,
      recoveredAt: now,
      updatedAt: now,
    },
    'Confirm legitimate club membership for Arsenal'
  );

  await planDelete(COLLECTIONS.USER_MEMBERSHIPS, `${SEASON_ID}_user-100002`, 'Test user membership for user-100002 (Sunderland test)');
  await planDelete(COLLECTIONS.USER_MEMBERSHIPS, `${SEASON_ID}_test_user_sunderland`, 'Synthetic user membership for Sunderland');
  const sunderlandClaimedAt = '2026-09-14T12:20:32.812Z';
  await planSet(
    COLLECTIONS.CLUBS,
    'club-sunderland',
    {
      isTaken: true,
      claimedByUserId: 'user-6128910148',
      claimedAt: sunderlandClaimedAt,
      recoveredAt: now,
      updatedAt: now,
    },
    'Confirm legitimate owner user-6128910148 for Sunderland'
  );
  await planSet(
    COLLECTIONS.CLUB_OCCUPANCIES,
    `${SEASON_ID}_club-sunderland`,
    {
      seasonId: SEASON_ID,
      clubId: 'club-sunderland',
      userId: 'user-6128910148',
      status: 'active',
      statusSeason: `active_${SEASON_ID}`,
      claimedAt: sunderlandClaimedAt,
      recoveredAt: now,
      updatedAt: now,
    },
    'Confirm legitimate occupancy for Sunderland'
  );
  await planSet(
    COLLECTIONS.CLUB_MEMBERSHIPS,
    `${SEASON_ID}_club-sunderland`,
    {
      seasonId: SEASON_ID,
      clubId: 'club-sunderland',
      userId: 'user-6128910148',
      status: 'active',
      claimedAt: sunderlandClaimedAt,
      recoveredAt: now,
      updatedAt: now,
    },
    'Confirm legitimate club membership for Sunderland'
  );

  // PART 7: Fixture Recovery: fix-comp-premier-league-2026-md1-bournemouth-vs-tottenham
  await planDelete(
    COLLECTIONS.RESULT_SUBMISSIONS,
    'sub-fix-comp-premier-league-2026-md1-bournemouth-vs-tottenham-audit-player-1',
    'Synthetic result submission for Bournemouth vs Tottenham'
  );
  await planDelete(
    COLLECTIONS.RESULT_SUBMISSIONS,
    'sub-fix-ctrl-1-audit-player-1',
    'Synthetic control result submission'
  );

  // Bournemouth vs Tottenham fixture reset to SCHEDULED (only 1 unilateral submission existed, do not guess)
  await planSet(
    COLLECTIONS.FIXTURES,
    'fix-comp-premier-league-2026-md1-bournemouth-vs-tottenham',
    {
      status: 'SCHEDULED',
      homeScore: null,
      awayScore: null,
      winnerClubId: null,
      resultConfirmedAt: null,
      recoveredAt: now,
      updatedAt: now,
    },
    'Reset contaminated fixture score to SCHEDULED with cleared scores and audit preservation'
  );

  // Sort operations canonically
  operations.sort((a, b) => a.path.localeCompare(b.path));

  // Compute canonical recovery plan hash
  const canonicalSummary = operations.map((op) => ({
    op: op.op,
    path: op.path,
    contentHash: op.contentHash,
    payload: op.payload,
  }));
  const planHash = computeHash(canonicalSummary);

  const recoveryPlan: RecoveryPlan = {
    projectId: status.projectId!,
    databaseId: status.databaseId!,
    seasonId: SEASON_ID,
    generatedAt: now,
    planHash,
    candidateResolutions: {
      arsenal: arsenalResolution,
      sunderland: sunderlandResolution,
    },
    operations,
  };

  // Ensure artifacts folder exists
  const artifactsDir = path.join(process.cwd(), 'artifacts');
  if (!fs.existsSync(artifactsDir)) {
    fs.mkdirSync(artifactsDir, { recursive: true });
  }

  const planFilePath = path.join(artifactsDir, 'recovery-plan.json');
  fs.writeFileSync(planFilePath, JSON.stringify(recoveryPlan, null, 2), 'utf8');

  console.log(`\nOperations Count: ${operations.length}`);
  console.log(`  - Deletions: ${operations.filter((o) => o.op === 'delete').length}`);
  console.log(`  - Sets/Updates: ${operations.filter((o) => o.op !== 'delete').length}`);
  console.log(`RECOVERY_PLAN_HASH: ${planHash}`);
  console.log(`Recovery plan written to: artifacts/recovery-plan.json`);

  if (isPlanMode) {
    console.log('\n================================================================');
    console.log('✓ PLAN GENERATED SUCCESSFULLY (STRICTLY READ-ONLY, ZERO WRITES)');
    console.log('================================================================');
    console.log('To apply this plan, run:');
    console.log(`APPLY_PRODUCTION_RECOVERY=true \\`);
    console.log(`EXPECTED_FIREBASE_PROJECT_ID=${EXPECTED_PROD_PROJECT_ID} \\`);
    console.log(`EXPECTED_FIRESTORE_DATABASE_ID=${EXPECTED_PROD_DATABASE_ID} \\`);
    console.log(`RECOVERY_PLAN_HASH=${planHash} \\`);
    console.log(`npm run recovery:contamination:apply\n`);
    return;
  }

  // --- APPLY MODE ---
  console.log('\n[PHASE 3] Validating Apply Preconditions & Safety Guards...');
  const applyFlag = process.env.APPLY_PRODUCTION_RECOVERY;
  const envProjId = process.env.EXPECTED_FIREBASE_PROJECT_ID;
  const envDbId = process.env.EXPECTED_FIRESTORE_DATABASE_ID;
  const envPlanHash = process.env.RECOVERY_PLAN_HASH;

  if (applyFlag !== 'true') {
    console.error('❌ FATAL: APPLY_PRODUCTION_RECOVERY=true is required to apply recovery.');
    process.exit(1);
  }
  if (envProjId !== EXPECTED_PROD_PROJECT_ID) {
    console.error(`❌ FATAL: EXPECTED_FIREBASE_PROJECT_ID must match ${EXPECTED_PROD_PROJECT_ID}`);
    process.exit(1);
  }
  if (envDbId !== EXPECTED_PROD_DATABASE_ID) {
    console.error(`❌ FATAL: EXPECTED_FIRESTORE_DATABASE_ID must match ${EXPECTED_PROD_DATABASE_ID}`);
    process.exit(1);
  }
  if (envPlanHash !== planHash) {
    console.error(`❌ FATAL: RECOVERY_PLAN_HASH mismatch!`);
    console.error(`  Expected from plan: ${planHash}`);
    console.error(`  Received in env:    ${envPlanHash}`);
    process.exit(1);
  }

  // Pre-apply verification: Re-read every affected document and verify content hash
  console.log('\n[PHASE 4] Pre-Apply State Verification (Drift Detection)...');
  for (const op of operations) {
    const fresh = await fetchDocumentState(db, op.collection, op.docId);
    if (fresh.exists !== op.exists || fresh.contentHash !== op.contentHash) {
      console.error(`❌ STATE DRIFT DETECTED on ${op.path}! Aborting apply.`);
      console.error(`  Planned content hash: ${op.contentHash}`);
      console.error(`  Current content hash: ${fresh.contentHash}`);
      process.exit(1);
    }
  }
  console.log('✓ All affected documents match plan hashes exactly. Zero drift detected.');

  // Backup
  const runId = `recovery_${Date.now()}_${crypto.randomBytes(4).toString('hex')}`;
  console.log(`\n[PHASE 5] Creating Durable Backups (Run ID: ${runId})...`);

  const backupData: any[] = [];
  const backupBatch = db.batch();

  for (const op of operations) {
    if (op.exists) {
      const backupEntry = {
        runId,
        collection: op.collection,
        docId: op.docId,
        path: op.path,
        previousData: op.currentData,
        backedUpAt: now,
      };
      backupData.push(backupEntry);

      const safeBackupDocId = `${runId}_${op.collection}_${op.docId}`.replace(/\//g, '_');
      const backupRef = db.collection('recovery_backups').doc(runId).collection('documents').doc(safeBackupDocId);
      backupBatch.set(backupRef, backupEntry);
    }
  }

  // Save local backup file
  const localBackupFile = path.join(artifactsDir, `recovery-backup-${runId}.json`);
  fs.writeFileSync(localBackupFile, JSON.stringify(backupData, null, 2), 'utf8');
  console.log(`✓ Local backup saved: artifacts/recovery-backup-${runId}.json`);

  // Commit Firestore backup
  await backupBatch.commit();
  console.log(`✓ Durable Firestore backup written under recovery_backups/${runId}/documents`);

  // Phase 6: Execute Mutations in Batches (max 400 ops)
  console.log('\n[PHASE 6] Applying Recovery Mutations...');
  const BATCH_LIMIT = 400;
  let batch = db.batch();
  let opCount = 0;

  for (const op of operations) {
    const ref = db.collection(op.collection).doc(op.docId);
    if (op.op === 'delete') {
      batch.delete(ref);
    } else if (op.op === 'set') {
      batch.set(ref, op.payload);
    } else if (op.op === 'update') {
      batch.update(ref, op.payload);
    }
    opCount++;

    if (opCount >= BATCH_LIMIT) {
      await batch.commit();
      batch = db.batch();
      opCount = 0;
    }
  }

  // Write new audit log documenting recovery execution (never delete existing audit logs!)
  const auditRef = db.collection(COLLECTIONS.AUDIT_LOGS).doc();
  batch.set(auditRef, {
    actorUserId: 'system-recovery-2026-09-14',
    action: 'PRODUCTION_CONTAMINATION_RECOVERY',
    timestamp: now,
    details: {
      runId,
      planHash,
      seasonId: SEASON_ID,
      operationsCount: operations.length,
      deletionsCount: operations.filter((o) => o.op === 'delete').length,
      updatesCount: operations.filter((o) => o.op !== 'delete').length,
      alavesLegitOwner: 'user-1238738998',
      barcelonaLegitOwner: 'user-8117945434',
      arsenalLegitOwner: 'user-7460059265',
      sunderlandLegitOwner: 'user-6128910148',
      releasedClubs: ['club-racing-santander', 'club-malaga', 'club-mallorca'],
      resetFixtureId: 'fix-comp-premier-league-2026-md1-bournemouth-vs-tottenham',
    },
  });

  await batch.commit();
  console.log(`✓ Recovery mutations applied successfully (${operations.length} operations).`);
  console.log(`✓ System recovery audit log created: ${auditRef.id}`);

  console.log('\n================================================================');
  console.log('✓ CONTROLLED PRODUCTION DATA RECOVERY APPLIED SUCCESSFULLY');
  console.log('================================================================\n');
}

// Execute CLI
if (process.argv[1] && process.argv[1].endsWith('applyProductionContaminationRecovery.ts')) {
  runRecovery().catch((err) => {
    console.error('\n❌ RECOVERY SCRIPT ERROR:', err);
    process.exit(1);
  });
}
