import assert from 'node:assert/strict';
import { designPreviewRequest, confirmDemoOpponent, resetDemoResults } from '../../lib/designPreviewData';
const values = new Map<string, string>();
(globalThis as any).window = { location: { origin: 'https://demo.example' } };
(globalThis as any).sessionStorage = {getItem: (k: string) => values.get(k) || null, setItem: (k: string,v: string) => values.set(k,v), removeItem: (k: string) => values.delete(k)};
(globalThis as any).fetch = () => { throw Error('Demo must never fetch a backend'); };
const before = await designPreviewRequest('/api/me/matches');
assert.equal(before.fixtures.length, 2);
const submitted = await designPreviewRequest('/api/fixtures/demo-match-0/result', {method: 'POST', body: JSON.stringify({homeScore: 2, awayScore: 1, proofUrl: 'https://example.com/proof.png'})});
assert.equal(submitted.fixture.status, 'PENDING_CONFIRMATION');
assert.equal(submitted.fixture.userSubmission.proofUrl, 'https://example.com/proof.png');
assert.equal((await designPreviewRequest('/api/competitions/demo-league-0/standings')).standings[0].points, 0);
confirmDemoOpponent();
assert.equal((await designPreviewRequest('/api/me/matches')).fixtures[0].status, 'CONFIRMED');
assert.equal((await designPreviewRequest('/api/competitions/demo-league-0/standings')).standings[0].points, 3);
await assert.rejects(designPreviewRequest('/api/admin/clubs/club-arsenal/release', {method: 'POST'}), /mavjud emas/);
await assert.rejects(designPreviewRequest('/api/fixtures/real-fixture/result', {method: 'POST'}), /mavjud emas/);
resetDemoResults();
assert.equal((await designPreviewRequest('/api/me/matches')).fixtures[0].status, 'SCHEDULED');
console.log('PASS isolated browser demo: proof, pending/confirmation, standings, reset and all unknown mutations blocked without network.');
