import assert from 'node:assert/strict';
import { initDatabase } from '../db';
import { getFirestoreDb } from '../firebase/admin';
import { COLLECTIONS } from '../firebase/collections';
import { getUserNotificationsFirestore, markSingleNotificationReadFirestore, markNotificationsReadFirestore, invalidateFirestoreCache } from '../firebase/firestoreStore';
import { getFreshKey, redisDelRaw, redisGetLkg, redisSetRaw, clearProcessMemoryForTest } from '../readModel/readModelStore';
import { persistNotificationReadState } from '../services/notificationReadState';

await initDatabase();
const db = getFirestoreDb();
const userId = 'isolated-read-user';
const key = `efluz:v1:user:${userId}:notifications:30`;
const first = { id: 'isolated-notif-one', userId, type: 'SYSTEM' as const, title: 'one', message: 'one', isRead: false, createdAt: '2026-01-01T00:00:00.000Z' };
const second = { ...first, id: 'isolated-notif-two', title: 'two' };
for (const notification of [first, second]) await db.collection(COLLECTIONS.NOTIFICATIONS).doc(notification.id).set(notification);
await redisSetRaw(key, { data: [first, second] }, 300);
assert.equal((await getUserNotificationsFirestore(userId))[0].isRead, false);
await markSingleNotificationReadFirestore(userId, first.id);
assert.equal((await db.collection(COLLECTIONS.NOTIFICATIONS).doc(first.id).get()).data()?.isRead, true);
invalidateFirestoreCache();
clearProcessMemoryForTest();
let reloaded = await getUserNotificationsFirestore(userId);
assert.equal(reloaded.find(n => n.id === first.id)?.isRead, true, 'Fresh Redis snapshot must not resurrect unread state on re-entry');
assert.equal(reloaded.find(n => n.id === second.id)?.isRead, false);
await redisDelRaw(getFreshKey(key));
invalidateFirestoreCache();
reloaded = await getUserNotificationsFirestore(userId);
assert.equal(reloaded.find(n => n.id === first.id)?.isRead, true, 'Permanent stale snapshot must retain read overlay');
assert.equal((await redisGetLkg<any[]>(key))?.data.length, 2, 'Do not delete recovery snapshot');
await assert.rejects(markSingleNotificationReadFirestore('different-user', second.id), /OWNERSHIP_MISMATCH/);
await markNotificationsReadFirestore(userId);
invalidateFirestoreCache();
assert.ok((await getUserNotificationsFirestore(userId)).every(n => n.isRead));
const future = { ...first, id: 'new-after-read-all', createdAt: '2099-01-01T00:00:00.000Z' };
await redisSetRaw(key, { data: [first, second, future] });
invalidateFirestoreCache();
assert.equal((await getUserNotificationsFirestore(userId)).find(n => n.id === future.id)?.isRead, false, 'New notifications must remain unread after mark-all');
await persistNotificationReadState(userId, '2020-01-01T00:00:00.000Z');
invalidateFirestoreCache();
assert.equal((await getUserNotificationsFirestore(userId)).find(n => n.id === second.id)?.isRead, true, 'Older concurrent acknowledgement must not undo a newer one');
await redisSetRaw('efluz:v1:user:isolated-other:notifications:30', { data: [{ ...first, userId: 'isolated-other' }] });
assert.equal((await getUserNotificationsFirestore('isolated-other'))[0].isRead, false, 'Read state is private per user');
console.log('PASS: re-entry, stale Redis, single/all read, new notification, concurrent timestamp and ownership isolation');
