import assert from 'node:assert/strict';
import { initDatabase } from '../db';
import { getFirestoreDb } from '../firebase/admin';
import { startMockUpstashBridge } from './mockUpstashBridge';
import { ReadModelKeys, redisSetRaw } from '../readModel/readModelStore';
import { generateGroundedTelegramAnswer } from '../services/telegramAiReadTools';
import { planAiAdminAction, handleAiAdminCommand, setTestAiAdminModelGenerator, setTestAiAdminHooks } from '../services/telegramAiAdminService';
import { saveAiAdminDraft, rememberDeliveredAiAdminDraft, getDeliveredAiAdminDraft, clearAiAdminDraft } from '../services/telegramAiAdminDraft';
import { DEFAULT_AI_CONFIG, setTestConfigOverride } from '../services/telegramAiConfigService';
import { getConversationIntent } from '../services/telegramAiConversationCommands';
import { getAiRedisClient } from '../services/telegramAiDeadline';

await initDatabase();
const bridge = await startMockUpstashBridge();
const signal = new AbortController().signal;
const payload = (text: string) => ({ updateId: 991001, messageId: 1, chatId: -1001, threadId: 3503, fromUser: { id: 5209126900 }, text });
const db = getFirestoreDb(), original = db.collection.bind(db);
let firestoreCalls = 0, writes = 0;
db.collection = (() => { firestoreCalls++; throw new Error('NO_FIRESTORE_FOR_PLANNING'); }) as any;
const call = (name: string, args: any, id: string) => ({ functionCalls: [{ name, args, id }], candidates: [{ content: { role: 'model', parts: [{ functionCall: { name, args, id }, thoughtSignature: id }] } }] });
try {
  process.env.GEMINI_API_KEY = 'test-only-not-a-real-key';
  process.env.TELEGRAM_BOT_TOKEN = '777:test-only';
  await redisSetRaw(ReadModelKeys.clubsWithOwners('season-2026-27'), { data: [{ id: 'club-heidenheim', name: '1. FC Heidenheim', leagueId: 'league-bundesliga', ownerUsername: 'actual_owner' }, { id: 'club-arsenal', name: 'Arsenal', leagueId: 'league-premier-league' }] });
  await redisSetRaw('efluz:v1:admin:user-directory', { data: [{ id: 'user-12345', username: 'actual_owner' }] });
  setTestConfigOverride({ ...DEFAULT_AI_CONFIG, enabled: true, allowedChatId: -1001, allowedThreadId: 3503 });
  setTestAiAdminHooks(async () => { writes++; return { status: 200, data: { success: true } }; });
  let rounds = 0;
  setTestAiAdminModelGenerator(async request => {
    rounds++;
    if (rounds === 1) return call('read_tournament_data', { dataset: 'clubs', club: 'Heidenheim' }, 'club-read');
    assert.equal(request.contents[1].parts[0].thoughtSignature, 'club-read');
    if (rounds === 2) return call('resolve_admin_user', { reference: '@actual_owner' }, 'user-read');
    assert.equal(request.contents[3].parts[0].thoughtSignature, 'user-read');
    assert.equal(request.contents[4].parts[0].functionResponse.id, 'user-read');
    assert.equal(request.contents[4].parts[0].functionResponse.response.result.user.id, 'user-12345');
    return { text: JSON.stringify({ action: 'club_assign', targetId: 'club-heidenheim', body: { targetUserId: 'user-12345' } }) };
  });
  const plan = await planAiAdminAction('Please assign Heidenheim to @actual_owner', '', signal);
  assert.equal(rounds, 3); assert.equal(plan.body.targetUserId, 'user-12345'); assert.equal(plan.body.expectedUsername, 'actual_owner');
  assert.equal(getConversationIntent('Please assign Heidenheim to @actual_owner'), 'admin');
  setTestAiAdminModelGenerator(async () => ({ text: JSON.stringify({ action: 'club_assign', targetId: 'club-arsenal', body: { targetUserId: '@actual_owner' } }) }));
  await assert.rejects(planAiAdminAction('Please assign Heidenheim to @actual_owner', '', signal), /mos kelmadi/);
  setTestAiAdminModelGenerator(async () => ({ text: JSON.stringify({ action: 'club_assign', targetId: 'club-heidenheim', body: { targetUserId: 'user-99999' } }) }));
  await assert.rejects(planAiAdminAction('Please assign Heidenheim to @actual_owner', '', signal), /taxmin qilmayman/);
  let unknownCalls = 0;
  const rejected = await generateGroundedTelegramAnswer({ ai: {} as any, model: 'mock', contents: [], systemPrompt: '', signal, maxToolRounds: 3, generate: async () => call('execute_admin_write', {}, 'bad'), read: async () => { unknownCalls++; return {}; } });
  assert.match(rejected, /aniqroq/); assert.equal(unknownCalls, 0);
  let capped = 0;
  await assert.rejects(generateGroundedTelegramAnswer({ ai: {} as any, model: 'mock', contents: [], systemPrompt: '', signal, maxToolRounds: 3, generate: async () => { capped++; return call('read_tournament_data', {}, String(capped)); }, read: async () => ({ data: [] }) }), /CLARIFY/);
  assert.equal(capped, 4);
  const p = payload('Heidenheimga biriktir');
  const question = await handleAiAdminCommand(p, signal);
  assert.ok(!question.includes('/ai_confirm'));
  assert.equal(await getDeliveredAiAdminDraft(payload('@actual_owner'), signal), null);
  await rememberDeliveredAiAdminDraft(p, question, 808, signal);
  assert.ok(await getDeliveredAiAdminDraft(payload('@actual_owner'), signal));
  assert.equal(await getDeliveredAiAdminDraft({ ...p, fromUser: { id: 7573478198 } }, signal), null);
  assert.equal(await getDeliveredAiAdminDraft({ ...p, threadId: 999 }, signal), null);
  assert.equal(await getDeliveredAiAdminDraft({ ...p, chatId: -1002 }, signal), null);
  assert.equal(await getDeliveredAiAdminDraft({ ...p, replyToMessage: { message_id: 808, from: { id: 888, is_bot: true } } }, signal), null);
  assert.equal(await getDeliveredAiAdminDraft({ ...p, forwarded: true }, signal), null);
  const preview = await handleAiAdminCommand(payload('@actual_owner'), signal);
  assert.match(preview, /\/ai_confirm/); assert.match(preview, /Heidenheim/);
  assert.equal(await getDeliveredAiAdminDraft(p, signal), null);
  await saveAiAdminDraft(p, p.text, question, signal);
  await rememberDeliveredAiAdminDraft(p, question, 809, signal);
  await handleAiAdminCommand(payload('bekor qil'), signal);
  assert.equal(await getDeliveredAiAdminDraft(p, signal), null);
  await getAiRedisClient(signal)!.set('efluz:v1:telegram:ai:draft:-1001:3503:5209126900', { request: p.text, question, deliveredMessageId: 809, expiresAt: Date.now() - 1 });
  assert.equal(await getDeliveredAiAdminDraft(p, signal), null);
  await clearAiAdminDraft(p, signal);
  assert.equal(writes, 0); assert.equal(firestoreCalls, 0);
  console.log('PASS sequential semantic read tools, signatures/IDs, verified user resolution, wrong target rejection, bounded rounds, delivered clarification continuation, actor/topic/reply isolation, cancellation/expiry; zero writes/Firestore, model mocked');
} finally {
  db.collection = original; setTestAiAdminModelGenerator(); setTestAiAdminHooks(); setTestConfigOverride(null); await bridge.close();
}
