/** Curated evaluation examples, not model training or automatic user-message collection. */
export const understandingCases = [
  ['remaining-reported', "Hozirgacha qaysi o'yinlar qoldi o'ynalmagan APLda?", 'fixtures'],
  ['remaining-short', 'APL oynalmaganlar', 'fixtures'],
  ['remaining-typo', 'APL oynamagan oyinlar', 'fixtures'],
  ['remaining-earlier', 'APL 10 turgacha qolgan oyinlar', 'fixtures'],
  ['remaining-round', 'APL 10 turdagi oynalmaganlar', 'fixtures'],
  ['remaining-all-season', 'APL butun mavsum oynalmagan oyinlar', 'fixtures'],
  ['remaining-english', 'Premier League unplayed matches', 'fixtures'],
  ['remaining-incomplete', 'La Liga yakunlanmagan uchrashuvlar', 'fixtures'],
  ['results-short', 'APL natijalar', 'fixtures'],
  ['results-round', 'APL 11 tur natijalari', 'fixtures'],
  ['results-through', 'APL 10 turgacha natijalar', 'fixtures'],
  ['results-played', 'La Liga oynalgan oyinlar', 'fixtures'],
  ['results-english', 'Premier League results', 'fixtures'],
  ['followup-round', '11 turdagichi?', 'fixtures'],
  ['followup-through', '10 turgacha?', 'fixtures'],
  ['followup-results', 'natijalarchi?', 'fixtures'],
  ['followup-remaining', 'qolganlarchi?', 'fixtures'],
  ['table', 'La Liga jadvalini tashla', 'standings'],
  ['table-followup', 'jadvalchi?', 'standings'],
  ['table-english', 'Premier League table', 'standings'],
  ['fixtures-round', 'La Liga 10 tur oyinlar jadvali', 'fixtures'],
  ['fixtures-selected', 'osha oyinni korsat', 'fixtures'],
  ['position', 'Brighton nechanchi orinda?', 'chat'],
  ['owner', 'Heidenheim egasi kim?', 'chat'],
  ['analysis', 'APL natijalari nega shunaqa?', 'chat'],
  ['prediction', 'Arsenal Chelsea kim yutadi?', 'chat'],
  ['banter', 'Arsenal haqida hazil qil', 'chat'],
  ['admin-assignment', '@actual_owner Heidenheimga biriktirgin', 'admin'],
  ['admin-release', 'Heidenheimni boshatgin', 'admin'],
  ['admin-score', 'Nottingham 5-1 Arsenal 11 tur buni kiritib qoygin', 'admin'],
  ['admin-clear-score', 'Inter Milan 10 tur natijasini ochir', 'admin'],
  ['admin-remove-match', 'APL oynalmagan oyinlarni ochir', 'admin'],
  ['admin-lock', 'La Liga 10-turni qulflang', 'admin'],
  ['confirm', 'tasdiqlayman', 'confirm'],
  ['cancel', 'bekor qil', 'cancel'],
  ['help', 'yordam', 'help'],
] as const;
