import assert from 'node:assert/strict';
import { canExportTournamentImage, imageFilename, matchdayImageModel, standingsImageModel, paintTournamentImage } from '../../lib/tournamentImage';
import type { Fixture, StandingsRow } from '../../types';
assert.equal(canExportTournamentImage(null),false);
assert.equal(canExportTournamentImage({isAdmin:false,isSuspended:false}),false);
assert.equal(canExportTournamentImage({isAdmin:true,isSuspended:true}),false);
assert.equal(canExportTournamentImage({isAdmin:true,isSuspended:false}),true);
const standings: StandingsRow[] = Array.from({length:20},(_,index)=>({position:20-index,clubId:'club-'+index,clubName:'Team '+index,shortName:'T',played:index,won:1,drawn:2,lost:3,goalsFor:5,goalsAgainst:6,goalDifference:-1,points:index}));
const table=standingsImageModel('La Liga','season-2026-27',standings,'uz');
assert.equal(table.rows.length,20);assert.equal(table.rows[0].position,1);assert.equal(standings[0].position,20);
assert.deepEqual(table.rows[0].stats,[19,1,2,3,5,6,-1,19]);
const fixture=(id:string,status:string,matchday=10,seasonId='season-2026-27'):Fixture=>({id,competitionId:'comp-serie-a-2026',seasonId,matchday,status:status as any,homeClubId:'club-inter',awayClubId:'club-milan',homeScore:0,awayScore:0,scheduledAt:'',createdAt:'',updatedAt:''});
const matches=matchdayImageModel('Serie A','season-2026-27',[fixture('id-md1','CONFIRMED'),fixture('pending','PENDING_CONFIRMATION'),fixture('disputed','DISPUTED'),fixture('old','CONFIRMED',10,'season-2025-26'),fixture('wrong-round','CONFIRMED',1)],10,'uz');
assert.equal(matches.rows.length,3);assert.equal(matches.rows.find(row=>row.score==='0 : 0')?.id,'club-inter');
assert.equal(matches.rows.filter(row=>row.score==='VS'&&row.status==='Tekshiruvda').length,2);
assert.equal(matches.round,'Tur 10');assert.equal(imageFilename('../comp:x','matchday',10),'efluz-compx-matchday-10.png');
const drawn:string[]=[];
const ctx:any={canvas:{width:0,height:0},fillRect(){},measureText(text:string){return{width:text.length*10}},fillText(text:string){drawn.push(text)},drawImage(){}};
paintTournamentImage(ctx,table);
assert.equal(ctx.canvas.width,1080);assert.ok(ctx.canvas.height>1500);
for(const row of standings)assert.ok(drawn.includes(row.clubName),'All table rows included, without viewport clipping');
assert.ok(drawn.includes('t.me/efluzbot'));
drawn.length=0;paintTournamentImage(ctx,matches);assert.ok(drawn.includes('0 : 0'));assert.ok(drawn.includes('Tekshiruvda'));
assert.equal(matchdayImageModel('Cup','season-2026-27',[{...fixture('tbd','SCHEDULED'),homeClubId:null,awayClubId:null}],10,'en').rows[0].name,'TBD');
console.log('PASS full-table PNG layout, stable standings statistics, canonical matchday selection, season isolation, zero-score draws, exclusion of unconfirmed scores and safe filenames');
