import assert from 'node:assert/strict';
import { getFirestoreDb } from '../firebase/admin';
import { firestoreCircuitBreaker } from '../firebase/circuitBreaker';
import { getReadMetrics, resetFirestoreReadMetrics } from '../firebase/firestoreStore';
import { getLeagueClubsFromReadModel, getOptionalCurrentClub, getCompetitionsFromReadModel, getCompetitionStandingsFromReadModel, clearProcessMemoryForTest, resetMemoryRedisStore, resetUpstashClient, redisSetRaw, redisGetFresh, persistReadSnapshot, readThroughReadModel } from '../readModel/readModelStore';
import { SEED_CLUBS, SEED_COMPETITIONS } from '../db/seed';
import { getNotificationControls } from '../services/notificationVisibility';

const db = getFirestoreDb();
await db.collection('users').doc('outage-owner').set({ username:'actual_owner', firstName:'Actual', lastName:'Owner' });
await db.collection('club_occupancies').doc('outage-claim').set({ seasonId:'season-2026-27', clubId:SEED_CLUBS[0].id, userId:'outage-owner', status:'active' });
for (const c of SEED_COMPETITIONS.filter(c => c.seasonId === 'season-2026-27')) await db.collection('competitions').doc(c.id).set({...c});
await db.collection('standings').doc('comp-premier-league-2026').set({rows:SEED_CLUBS.filter(c => c.leagueId === 'league-premier-league').map((c,i) => ({clubId:c.id,position:i+1,played:1,won:1,drawn:0,lost:0,goalsFor:1,goalsAgainst:0,goalDifference:1,points:3}))});
const originalFetch = globalThis.fetch;
let attempts = 0;
globalThis.fetch = (async () => { attempts++; throw new Error('ERR Upstash current Fixed plan limits'); }) as typeof fetch;
process.env.UPSTASH_REDIS_REST_URL = 'https://redis-outage.invalid';
process.env.UPSTASH_REDIS_REST_TOKEN = 'isolated-test';
resetUpstashClient(); resetMemoryRedisStore(); firestoreCircuitBreaker.reset(); resetFirestoreReadMetrics();
try {
  const results = await Promise.all(['league-premier-league','league-la-liga','league-serie-a','league-bundesliga','league-ligue-1'].map(id => getLeagueClubsFromReadModel(id,'season-2026-27')));
  assert.deepEqual(results.map(r => r.clubs.length),[20,20,20,18,18]);
  assert(results.every(r => r.degraded));
  const owner = results.flatMap(r => r.clubs).find(c => c.id === SEED_CLUBS[0].id) as any;
  assert.equal(owner.ownerUserId,'outage-owner');
  assert.equal(owner.ownerUsername,'actual_owner');
  assert.equal(getReadMetrics().readsByFunction.buildClubsSnapshot,1);
  assert.equal(getReadMetrics().readsByFunction['buildClubsSnapshot:owner'],1);
  const firstAttempts = attempts;
  clearProcessMemoryForTest();
  const me = await getOptionalCurrentClub('outage-owner');
  assert.equal(me.currentClub?.id,SEED_CLUBS[0].id);
  assert.equal(me.currentClubStatus,'resolved');
  assert.equal(getReadMetrics().readsByFunction.buildClubsSnapshot,1,'No rebuild after L1 expiration; ephemeral snapshot reused');
  assert((await getCompetitionsFromReadModel()).competitions.length > 0);
  const standings = await getCompetitionStandingsFromReadModel('comp-premier-league-2026');
  assert.equal(standings.standings.length,20);
  assert.equal(standings.standings[0].points,3);
  assert.equal(firestoreCircuitBreaker.getStatus().state,'CLOSED','Redis failure must not trip Firestore circuit');
  await assert.rejects(redisSetRaw('critical-durable-write',{data:[1]}),/REDIS_REQUIRED_FOR_DURABLE_SNAPSHOT/,'Mutation persistence must remain fail-closed');
  process.env.NODE_ENV = 'production';
  await assert.rejects(getNotificationControls(),/NOTIFICATION_CONTROLS_UNAVAILABLE/,'Never expose hidden notifications if visibility controls are unavailable');
  process.env.NODE_ENV = 'test';
  await persistReadSnapshot('outage-empty-guard',{data:[1]});
  await assert.rejects(persistReadSnapshot('outage-empty-guard',{data:[]}),/SNAPSHOT_REJECTED/);
  assert.deepEqual((await redisGetFresh<number[]>('outage-empty-guard'))?.data,[1]);
  await assert.rejects(readThroughReadModel({key:'unavailable-authority',firestoreFetcher:async () => {throw Object.assign(new Error('quota exceeded'),{code:8});}}),/Failed to load authoritative/);
  assert.equal(firestoreCircuitBreaker.getStatus().state,'OPEN','Real Firestore quota still opens circuit');
  assert.equal(attempts, firstAttempts,'Outage transport cooldown avoids subsequent Redis calls');
  console.log('PASS configured Redis outage: five league reads coalesce, exact owner/profile/catalog/standings load, bounded process cache reused, strict mutation durability and notification privacy preserved, actual quota fails closed');
} finally { globalThis.fetch = originalFetch; process.env.NODE_ENV = 'test'; resetUpstashClient(); }
