import assert from 'node:assert/strict';
import fs from 'node:fs';
const source = fs.readFileSync('src/components/CupBracketsView.tsx', 'utf8');
const start = source.indexOf('  const loadCupFixtures = useCallback(async () => {');
const end = source.indexOf('\n  }, [', start);
assert.ok(start >= 0 && end > start);
const body = source.slice(start, end).split('async () => {')[1];
const make = new Function('api', 'selectedCupId', 'fixtureScope', 'currentFixtureScope', 'fixtureRequest', 'setCupFixtures', 'setIsLoading', 'setError', 'setSelectedFixtureForSubmit', 'return async () => {'+body+'}');
const pending = new Map<string, { resolve: (v: any) => void; reject: (e: any) => void }>();
const api = {getCompetitionFixtures:(id:string)=>new Promise((resolve,reject)=>pending.set(id,{resolve,reject}))};
let fixtures:any[]=[]; let loading=false; let error:any=null;
const scope={current:'season-a:cup-a'}, request={current:0};
const loader=(cup:string,season='season-a')=>make(api,cup,`${season}:${cup}`,scope,request,(f:any[])=>fixtures=f,(v:boolean)=>loading=v,(e:any)=>error=e,()=>{});
const oldLoader=loader('cup-a');const old=oldLoader();
scope.current='season-a:cup-b';const latest=loader('cup-b')();
pending.get('cup-b')!.resolve({fixtures:[{id:'b'}]});await latest;
assert.equal(fixtures[0].id,'b'); assert.equal(loading,false);
pending.get('cup-a')!.resolve({fixtures:[{id:'a'}]});await old;
assert.equal(fixtures[0].id,'b'); assert.equal(loading,false);
await oldLoader();assert.equal(fixtures[0].id,'b');
const beforeError=loader('cup-b')();
scope.current='season-b:cup-c';const current=loader('cup-c','season-b')();
pending.get('cup-b')!.reject(Error('old request failed'));await beforeError;
assert.equal(error,null);assert.equal(loading,true);
pending.get('cup-c')!.resolve({fixtures:[]});await current;
assert.equal(loading,false);assert.deepEqual(fixtures,[]);
console.log('PASS late cup success/error ignored; stale callback cannot refetch previous cup; season switch and empty state remain correct.');
